force-app/main/default/objects/Bank_Account__c/Bank_Account__c.object-meta.xml
<CustomObject>
    <label>Bank Account</label>
    <nameField>
        <label>Bank Account Reference</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bank Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Bank_Account__c/fields/Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Account_Number__c</fullName>
    <label>Account Number</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bank_Account__c/fields/Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Type__c</fullName>
    <label>Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CURRENT</fullName>
            </value>
            <value>
                <fullName>SAVINGS</fullName>
            </value>
            <value>
                <fullName>ISA</fullName>
            </value>
            <value>
                <fullName>BUSINESS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Bank_Account__c/fields/Balance__c.field-meta.xml
<CustomField>
    <fullName>Balance__c</fullName>
    <label>Balance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Bank_Account__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bank Accounts</relationshipLabel>
    <relationshipName>Bank_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Bank_Account__c/fields/IBAN__c.field-meta.xml
<CustomField>
    <fullName>IBAN__c</fullName>
    <label>IBAN</label>
    <length>34</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bank_Account__c/fields/Is_Dormant__c.field-meta.xml
<CustomField>
    <fullName>Is_Dormant__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Dormant</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Bank_Account__c/fields/Last_Transaction_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Transaction_Date__c</fullName>
    <label>Last Transaction Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Bank_Account__c/fields/Overdraft_Limit__c.field-meta.xml
<CustomField>
    <fullName>Overdraft_Limit__c</fullName>
    <label>Overdraft Limit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Bank_Account__c/fields/Sort_Code__c.field-meta.xml
<CustomField>
    <fullName>Sort_Code__c</fullName>
    <label>Sort Code</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Card_Transaction__c/Card_Transaction__c.object-meta.xml
<CustomObject>
    <label>Card Transaction</label>
    <nameField>
        <label>Transaction Reference</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Card Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Card_Transaction__c/fields/Bank_Account__c.field-meta.xml
<CustomField>
    <fullName>Bank_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bank Account</label>
    <referenceTo>Bank_Account__c</referenceTo>
    <relationshipLabel>Card Transactions</relationshipLabel>
    <relationshipName>Card_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/BankAccountLightningController.cls
public without sharing class BankAccountLightningController {

    public static final String CORE_ENDPOINT = 'http://core.northbridge-bank.com/accounts';
    public static final String CORE_API_KEY = 'nbk_core_9f2c8a71b4de4c0e8a13f7d6b2e9c445';
    public static final Id DEFAULT_BRANCH_ID = '0018e000000BrNcHAAQ';

    @AuraEnabled
    public static List<Bank_Account__c> getAccountsForCustomer(String customerId) {
        return [SELECT Id, Account_Number__c, Sort_Code__c, IBAN__c, Balance__c,
                       Overdraft_Limit__c, Account_Type__c, Is_Dormant__c, Last_Transaction_Date__c
                FROM Bank_Account__c WHERE Customer__c = :customerId];
    }

    @AuraEnabled
    public static List<Bank_Account__c> searchAccounts(String searchTerm, String accountType, String sortBy) {
        String soql = 'SELECT Id, Account_Number__c, Sort_Code__c, Balance__c, Account_Type__c ' +
                      'FROM Bank_Account__c WHERE Account_Number__c LIKE \'%' + searchTerm + '%\'';
        soql += ' AND Account_Type__c = \'' + accountType + '\'';
        soql += ' ORDER BY ' + sortBy;
        return Database.query(soql);
    }

    @AuraEnabled
    public static List<Bank_Account__c> getAllAccounts() {
        return [SELECT Id, Account_Number__c, Sort_Code__c, IBAN__c, Balance__c, Customer__c
                FROM Bank_Account__c];
    }

    @AuraEnabled
    public static Bank_Account__c updateOverdraftLimit(String accountId, Decimal newLimit) {
        Bank_Account__c acct = [SELECT Id, Overdraft_Limit__c, Account_Number__c
                                FROM Bank_Account__c WHERE Id = :accountId LIMIT 1];
        acct.Overdraft_Limit__c = newLimit;
        update acct;
        System.debug('Limit updated on ' + acct.Account_Number__c + ' key ' + CORE_API_KEY);
        return acct;
    }

    @AuraEnabled
    public static void closeAccounts(List<String> accountIds, String reasonCode, String narrative) {
        for (String accountId : accountIds) {
            Bank_Account__c acct = [SELECT Id, Balance__c, Customer__c, Account_Number__c
                                    FROM Bank_Account__c WHERE Id = :accountId];

            List<Card_Transaction__c> txns = [SELECT Id FROM Card_Transaction__c
                                              WHERE Bank_Account__c = :acct.Id];
            delete txns;

            List<Account> customers = [SELECT Id, Description FROM Account WHERE Id = :acct.Customer__c];
            for (Account customer : customers) {
                customer.Description = 'Closed ' + reasonCode + ' ' + narrative;
                update customer;
            }

            acct.Is_Dormant__c = true;
            update acct;
        }
    }

    @AuraEnabled
    public static Decimal getTotalBalance(String customerId) {
        List<Bank_Account__c> accounts = [SELECT Id, Balance__c FROM Bank_Account__c
                                          WHERE Customer__c = :customerId];
        Decimal total = 0;
        for (Bank_Account__c acct : accounts) {
            if (acct.Balance__c != null) total = total + acct.Balance__c;
        }
        return total;
    }

    @AuraEnabled
    public static Integer countAccounts() {
        List<Bank_Account__c> all = [SELECT Id FROM Bank_Account__c];
        return all.size();
    }

    @AuraEnabled
    public static String syncWithCore(String accountNumber, String sortCode) {
        HttpRequest req = new HttpRequest();
        req.setEndpoint(CORE_ENDPOINT + '?an=' + accountNumber + '&sc=' + sortCode);
        req.setMethod('GET');
        req.setHeader('X-Api-Key', CORE_API_KEY);
        Http h = new Http();
        HttpResponse res = null;
        try {
            res = h.send(req);
        } catch (Exception e) {
        }
        return res.getBody();
    }

    private static Decimal legacyBalanceModel(Decimal balance) {
        return balance < 0 ? 0 : balance;
    }
}